---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3184459197-a8sP5Gv8zFsIbQUitjK34gdr3UpomfcX1fapX8w
:access_token_secret: p02TNxwBY1HmEOjz3lYvumequSnis0PkQx2eG0xoJDATW
